### PR TITLE
feat: parse issue body markdown

### PR DESCRIPTION
**Pull request by erickzhao**
This PR adds issue body parsing according to https://github.com/electron/bugbot/blob/main/.github/ISSUE_TEMPLATE/bug_report.yml.

It parses the string into a markdown abstract syntax tree, and grabs the content from the AST. I figured this would be more extendable than parsing the string directly using regex, but let me know if there are any issues with this approach.

There's no further functionality here, so to test things out, I make the bot comment if the parsing was successful.

See https://github.com/erickzhao/bugbot/issues/2

### CODE REVIEW

**Review by ckerr — COMMENTED** [review]
Tests?

**Comment by erickzhao** [comment]
Oops, totally forgot. I'll take a look at how our existing bots are tested and build some test infrastructure here. :)

**Review by clavin — CHANGES_REQUESTED** [review]
Maybe I'm thinking too far head, but question: should this bot be proactive in identifying things it can run in an issue, or should it instead be invoked like a command? The benefit of the latter is that we can easily activate the bot after some back-and-forth, e.g. asking the reporter to create a fiddle.

Also +1 to the comment on adding testing!

**Comment by ckerr** [comment]
> Maybe I'm thinking too far head, but question: should this bot be proactive in identifying things it can run in an issue, or should it instead be invoked like a command? The benefit of the latter is that we can easily activate the bot after some back-and-forth, e.g. asking the reporter to create a fiddle.

The latter is probably useful for testing and for prodding the bot in the right direction when it gets stuck and so that would be super useful!

IMO the steady state should be the bot "just works" without commands in comments though. So TLDR is "add code to support comment commands IFF it's useful to you in development but don't block on it."

**Review by ckerr — APPROVED** [review]
LGTM. I think we should merge this so that we can move to the next pieces.

**Review by clavin — APPROVED** [review]

**Pull request merged**
