### PR TITLE
feat: simple bisect runner server

### PR DESCRIPTION
**Pull request by clavin**
A simple HTTP server that will forward bisect requests to Fiddle and parse the output when it returns.

The server has one endpoint `POST /fiddle/bisect` which takes a JSON body for the parameters:

```json
{
	"goodVersion": "a.b.c",
	"badVersion": "x.y.z",
	"gistId": "0123456789abcdef0123456789abcdef"
}
```

It then passes those parameters to Fiddle to run a bisect with. Once that is done, it will attempt to parse the output from Fiddle and determine if the bisect succeeded or not and (if it did succeed) what versions it narrowed down to. It returns this information as JSON.

**Bisect failed** (could not narrow down to two versions):

```json
{ "success": false }
```

**Bisect succeeded**:

```json
{
	"success": true,
	"goodVersion": "n.n.n",
	"badVersion": "m.m.m",
}
```

**Note**: the server expects the environment variable `FIDDLE_EXEC_PATH` to be set to the Fiddle binary so it can call it.

### CODE REVIEW

**Review by erickzhao — CHANGES_REQUESTED** [review]
Seems straightforward enough! LGTM, aside from one small copy/paste typo.

Which OSes have you tested on so far?

**Comment by clavin** [comment]
I've only tested on the Mac I've written this on, I'll also try it out on Windows and report back here.

**Comment by clavin** [comment]
✅ Tested it on Windows and it ran just fine.

**Review by erickzhao — APPROVED** [review]
Code LGTM!

**Pull request merged**
